### ISSUE TITLE
What are you basically creating so we can offer a hand? 

### ISSUE THREAD

**Issue by AnthonyByansi** [Wallace-Karira-Muraya/Mwangaza-Bidii-Project#1]
Thanks for reaching out!

Well, i am running a community based organization in my entire village and i will be more than happy for an assistance.

https://www.mwangazabidiiproject.org

Thank you!

**Comment by Wallace-Karira-Muraya** [comment]
Oh Yes, just to let you that i have sent a mail for more information's where i will be looking forward to hearing from you soonest with a positive response.

Thanks.
